### ISSUE TITLE
Support deploying guacamole with access from a deployment server

### ISSUE THREAD

**Issue by cdosborn** [calvinmclean/ansible-guacamole-server#31]
When we deployed atmosphere we had to manually enable ssh access from the deploy host -> guacamole server. Gucamole could add an entry to its authorized keys, so a given deploy host would have access.

**Comment by calvinmclean** [comment]
Just to clarify, you mean:
1. Add SSH public key to vars (the key that Atmosphere uses)
2. Add task to add this key to Guacamole server's authorized keys
3. Now `atmosphere-ansible` can send keys to Guacamole server during instance deploy

Correct?

**Comment by calvinmclean** [comment]
Resolved by 654fb0a382dc88bb8d00338749210eb61709f552
